var config={};
var defaultConfig={
	mode:"new",
	mode_new:{
		settings:{
			enable:true,
			back:false,
			all:false,
			deep:false
		},
		rule_domain:[],
		rule_page:[]
	},
	mode_current:{
		settings:{
			enable:true,
			all:false,
			deep:false
		},
		rule_domain:[],
		rule_page:[]	
	}
}
var otb={
	loadConf:function(){
		chrome.storage.sync.get(function(items){
			if(!items.mode){
				config=defaultConfig;
				chrome.storage.sync.set(config,function(){});
			}
			else{
				config=items;
			}
			otb.init();
		})	
	},
	init:function(){
		otb.setIcon();
	},
	saveConf:function(){
		chrome.storage.sync.clear(function(){
			chrome.storage.sync.set(config);
		})
		otb.setIcon();
	},
	setIcon:function(){
		chrome.browserAction.setIcon({path:{38:"../img/"+config.mode+".png"}});
		chrome.browserAction.setTitle({title:chrome.i18n.getMessage("nav_"+config.mode)})
	}
}

chrome.runtime.onMessage.addListener(function(message,sender,sendResponse) {
	if(message.type=="evt_getconf"){
		sendResponse(config)
	}
	if(message.type=="open"){
		if(config.mode=="new"){
			if(config.mode_new.settings.back){
				chrome.tabs.create({url:message.url,active:false});
			}else{
				chrome.tabs.create({url:message.url});
			}
		}else{
			chrome.tabs.update({url:message.url});
		}
		sendResponse({opent:true})	;
	}
	if(message.type=="config_afteraction"){
		config=message.value;
		otb.saveConf();
	}
	if(message.type=="loadconfig"){
		otb.loadConf();
	}
	if(message.type=="saveconfig"){
		config=message.value;
		otb.saveConf();
	}
});
otb.loadConf();